### PR TITLE
patched empire module

### PR DESCRIPTION
**Pull request by theiosif**
I am working with the Cryton version `tag 2.1.0`, prerequisites as docker; hive and worker installed on Kali with pipx.

Upon trying out the basic empire windows example, I got some errors indicating a typecast error, i.e. `Key 'session_id' error:\n11 should be instance of 'str'`. During patching I also encountered `"MSF session not found."`.

Solving that, the next encountered errors came from `deploy_agent`, in `session_to_use.execute_in_shell(payload)`: `SessionShell.execute_in_shell() missing 1 required positional argument: 'arguments'`. I looked at the msf wrapper code and adjusted accordingly.

I'm sure that my patch can be cleaned up a bit before merging, as I'm unfamiliar with the broad picture of the codebase.

### CODE REVIEW

**Comment by SadParad1se** [comment]
Hi,
Thank you for your PR!
I will take a look at it as soon as possible.

**Comment by SadParad1se** [comment]
Please re-open the pull request with `stable/2` as the target branch. Once done, please close this PR, and we will move the discussion there.

**Comment by SadParad1se** [comment]
The root cause of the first error is an outdated validation at https://github.com/CSIRT-MU/Cryton/blob/stable/2/cryton/worker/task.py#L266.
This can be fixed by updating `str` to `int`:
```
SchemaOptional(co.SESSION_ID): int,
```

With that, the changes in `cryton/hive/models/step.py` can be dropped.

File: cryton/worker/empire.py [hunk 1]
```diff
@@ -230,7 +230,7 @@ async def deploy_agent(arguments: dict) -> dict:
     if session_id:
         metasploit_obj = MetasploitClientUpdated()
         try:
-            session_to_use = metasploit_obj.sessions.get(session_id)
+            session_to_use = metasploit_obj.sessions.get(int(session_id))
```
Comment (SadParad1se) [inline cryton/worker/empire.py:233]: Once the validation is updated, please revert this change.

File: cryton/worker/empire.py [hunk 2]
```diff
@@ -240,7 +240,7 @@ async def deploy_agent(arguments: dict) -> dict:
         logger.logger.debug(
             "Deploying agent via MSF session.", session_id=session_id, payload=payload, target_ip=target_ip
         )
-        session_to_use.execute_in_shell(payload)
+        session_to_use.execute_in_shell(executable=''.join(payload.split()[:1]).strip(), arguments=payload.split()[1:])
```
Comment (SadParad1se) [inline cryton/worker/empire.py:243]: Could I suggest a temporary variable?
```suggestion
        payload_tmp = payload.split()
        session_to_use.execute_in_shell(payload_tmp[0], payload_tmp[1:])
```

Comment (theiosif) [reply cryton/worker/empire.py]: Addressed in [dc336a6](https://github.com/CSIRT-MU/Cryton/pull/1/commits/dc336a6e825faeb503e169d4885a43a21ab3d08f), thanks for the input!

File: cryton/worker/empire.py (hunk 1 above)
Comment (theiosif) [reply cryton/worker/empire.py]: Addressed in [dc336a6](https://github.com/CSIRT-MU/Cryton/pull/1/commits/dc336a6e825faeb503e169d4885a43a21ab3d08f), thanks for the input!

**Comment by SadParad1se** [comment]
I've released a new [2.1.1](https://gitlab.ics.muni.cz/cryton/cryton/-/releases/2.1.1) version. 
Thank you for your contribution!
